Tabs instead of spaces.  Formating.

diff --git a/vpn b/vpn
--- a/vpn
+++ b/vpn
@@ -1,10 +1,11 @@
 #!/bin/bash
-#: Title:	: vpn
-#: Author	: clewsy (clews.pro)
-#: Description	: Kills any existing vnp connection then establishes a new session.  Uses openvpn.
-#: Options	: -c	Cancels/kills current vpn connection without establishing new.
-#:		: -k	Kills/cancles current vpn connection without establishing new.
-#:		: -h	Help (print usage then exit).
+#: Title:       : vpn
+#: Author       : clewsy (clews.pro)
+#: Description  : Kills any existing vnp connection then establishes a new
+#:              : session.  Uses openvpn.
+#: Options      : -c - Cancels/kills current vpn connection.
+#:              : -k - Kills/cancles current vpn connection.
+#:              : -h - Help (print usage then exit).
 
 ## Exit codes.
 SUCCESS=0
@@ -22,103 +23,104 @@ BOLD="\033[01;37m"
 RESET="\033[0m"
 
 ## Define the default vpn config file to be used by openvpn.
-## This is ignored if the user provides an argument defining an alternate config file.
+## This is ignored if the user provides an argument defining a config file.
 DEFAULT_CONF="/home/b4t/openvpn/Windscribe-Australia_UDP.ovpn"
 
-## Define and clear a temp file into which ifconfig.co/json data will be entered and then parsed.
+## Create an empty temp file into which json data will be held and then parsed.
 TEMP_FILE="/tmp/vpn_tempfile"
 > "${TEMP_FILE}"
 
 USAGE="
 Usage: ${0##*/} <option> [openvpn config file]
 Valid options:
-	-c	Cancel running vpn. (Same as -k)
-	-k	Kill running vpn. (Same as -c)
-	-h	Help - Print this usage and exit.
-If no openvpn config file is entered, the default will be used (${DEFAULT_CONF}). 
+    -c    Cancel running vpn. (Same as -k)
+    -k    Kill running vpn. (Same as -c)
+    -h    Help - Print this usage and exit.
+If no openvpn config file is entered, the default will be used:
+${BOLD}${DEFAULT_CONF}${RESET} 
 "
-##########Interpret options
+########## Interpret options
 while getopts 'ckh' OPTION; do
-	case "$OPTION" in
-		c|k)	printf "%b" "\nCancelling vpn.\n\n"	## -c (cancel) or -k (kill) will kill any running openvpn instance.
-			sudo pkill openvpn
-			exit ${SUCCESS};;
-		h)	printf "%b" "${USAGE}\n"		## -h option just prints the usage then quits.
-			exit ${SUCCESS};;			## Exit successfully.
-		?)	printf "%b" "Invalid option/s.\n${USAGE}\n"
-			exit ${BAD_USAGE};;
-	esac
+    case "$OPTION" in
+        c|k)    printf "%b" "\nCancelling vpn.\n\n"
+                sudo pkill openvpn
+                exit ${SUCCESS} ;;
+        h)      printf "%b" "${USAGE}\n"
+                exit ${SUCCESS} ;;
+        ?)      printf "%b" "Invalid option/s.\n${USAGE}\n"
+                exit ${BAD_USAGE} ;;
+    esac
 done
-shift $((OPTIND -1))	## This ensures only non-option arguments are considered arguments when referencing $#, #* and $n.
+shift $((OPTIND -1))
 
-##########Check correct usage
+########## Check correct usage
 case $# in
-	0|1)	;;	## There should be 0 or 1 argument/s.
-	*)	printf "%b" "\n${RED}Error${RESET}: Too many arguments.  Quitting.\n${USAGE}\n"
-		exit ${BAD_USAGE};;
+    0|1)    ;;  ## There should be 0 or 1 argument/s.
+    *)      printf "%b" "\n${RED}Error${RESET}: Too many arguments.  Quitting.\n${USAGE}\n"
+            exit ${BAD_USAGE};;
 esac
 
-##########Define openvpn config file.
-VPN_FILE=${1-"${DEFAULT_CONF}"}	## First argument is the openvpn config file.  If not provided, set default.
+########## Define openvpn config file.
+VPN_FILE=${1-"${DEFAULT_CONF}"}
 
-##########Validate openvpn config file.
-if [ ! -f "${VPN_FILE}" ]; then	## If file is not a regular file or is missing.
-	printf "%b" "\n${RED}Error${RESET}: Invalid openvpn config file.  Quitting.\n${USAGE}\n"
-	exit ${BAD_CONFIG}
+########## Validate openvpn config file.
+if [ ! -f "${VPN_FILE}" ]; then ## If file is missing or not a regular file.
+    printf "%b" "\n${RED}Error${RESET}: Invalid openvpn config file.  Quitting.\n${USAGE}\n"
+    exit ${BAD_CONFIG}
 fi
 
-##########Ensure curl is installed.
+########## Ensure curl is installed.
 if ! command -v curl > /dev/null; then
-	printf "%b" "\n${RED}Error${RESET}: curl is not installed.  Quitting.\n\n"
-	exit ${NO_CURL}
+    printf "%b" "\n${RED}Error${RESET}: curl is not installed.  Quitting.\n\n"
+    exit ${NO_CURL}
 fi
 
-##########Kill current openvpn instance before creating new.
+########## Kill current openvpn instance before creating new.
 printf "%b" "\nKilling any running instances of openvpn.\n\n"
 sudo pkill openvpn
 
-##########Download current data from ifconfig.co into TEMP_FILE (this is the info without the vpn active).
+########## Download current data from ifconfig.co into TEMP_FILE
 if ! curl --silent --connect-timeout 5 --max-time 10 --output "${TEMP_FILE}" ifconfig.co/json ; then
-	printf "%b" "${RED}Error${RESET}: Failed to pull data from \"ifconfig.co/json\".  Quitting...\n\n"
-	exit ${NO_IFCONFIG_CO}
+    printf "%b" "${RED}Error${RESET}: Failed to pull data from \"ifconfig.co/json\".  Quitting...\n\n"
+    exit ${NO_IFCONFIG_CO}
 fi
 
-##########Parse specific details from the temp file.
+########## Parse specific details from the temp file.
 CURRENT_IP=$(grep -m 1 "ip" "${TEMP_FILE}" | cut -d "\"" -f 4)
 CURRENT_CITY=$(grep "city" "${TEMP_FILE}" | cut -d "\"" -f 4)
 
-##########Print out the current ip and city (without vpn).
+########## Print out the current ip and city (without vpn).
 printf "%15b%b" "Current ip : " "${BOLD}${CURRENT_IP}${RESET}\n"
 printf "%15b%b" "Current city : " "${BOLD}${CURRENT_CITY}${RESET}\n"
 
-##########Connect to the vpn.
+########## Connect to the vpn.
 printf "%b" "\nRunning openvpn using config file at \"${BLUE}${VPN_FILE}${RESET}\"\n"
 printf "%b" "\"${0##*/} -c\" to cancel/kill vpn.\n"
-if ! sudo openvpn --config "${VPN_FILE}" --daemon ; then	## Execute openvpn. Exit script if it fails.
-	rm "${TEMP_FILE}"
-	printf "%b" "\n${RED}Error:${RESET} openvpn failed. Quitting\n\n"
-	exit ${OPENVPN_FAIL}
+if ! sudo openvpn --config "${VPN_FILE}" --daemon ; then    ## Execute openvpn.
+    rm "${TEMP_FILE}"
+    printf "%b" "\n${RED}Error:${RESET} openvpn failed. Quitting\n\n"
+    exit ${OPENVPN_FAIL}
 fi
 
-##########Loop until the vpn is active - determined by a change in the ip.
+########## Loop until the vpn is active - determined by a change in the ip.
 NEW_IP=${CURRENT_IP}
 while [ "${NEW_IP}" = "${CURRENT_IP}" ]
 do
-	if ! curl --silent --connect-timeout 5 --max-time 10 --output "${TEMP_FILE}" ifconfig.co/json ; then
-		rm "${TEMP_FILE}"
-		printf "%b" "\n${RED}Error${RESET}: Failed to pull data from \"fconfig.co/json\".  Quitting...\n\n"
-		exit ${NO_IFCONFIG_CO}
-	fi
-	NEW_IP=$(grep -m 1 "ip" "${TEMP_FILE}" | cut -d "\"" -f 4)
+    if ! curl --silent --connect-timeout 5 --max-time 10 --output "${TEMP_FILE}" ifconfig.co/json ; then
+        rm "${TEMP_FILE}"
+        printf "%b" "\n${RED}Error${RESET}: Failed to pull data from \"fconfig.co/json\".  Quitting...\n\n"
+        exit ${NO_IFCONFIG_CO}
+    fi
+    NEW_IP=$(grep -m 1 "ip" "${TEMP_FILE}" | cut -d "\"" -f 4)
 done
 NEW_CITY=$(grep "city" "${TEMP_FILE}" | cut -d "\"" -f 4)
 
-##########Print out the new apparent ip & city.
+########## Print out the new apparent ip & city.
 printf "%b" "\n${GREEN}Connected.${RESET}\n\n"
 printf "%11b%b" "New ip : " "${BOLD}${NEW_IP}${RESET}\n"
 printf "%11b%b" "New city : " "${BOLD}${NEW_CITY}${RESET}\n\n"
 
-##########Delete the temp file.
+########## Delete the temp file.
 rm "$TEMP_FILE"
 
 exit ${SUCCESS}
